// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJdAkP6VA4TIudb9_IIU7qe3S0r1_nog',
    appId: '1:639013215151:web:1995cdd630c4282a0aad5a',
    messagingSenderId: '639013215151',
    projectId: 'kpikomida',
    authDomain: 'kpikomida.firebaseapp.com',
    databaseURL: 'https://kpikomida-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpikomida.firebasestorage.app',
    measurementId: 'G-P9BT3CYT7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRooW7MxGLIrD-R3AqYej7RNtEMyhY0Jw',
    appId: '1:639013215151:android:79d6171d3352c28b0aad5a',
    messagingSenderId: '639013215151',
    projectId: 'kpikomida',
    databaseURL: 'https://kpikomida-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpikomida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ncymf15NZpArPBXK2Ss5jPLzZWC4ye4',
    appId: '1:639013215151:ios:562d2f22911dc4e80aad5a',
    messagingSenderId: '639013215151',
    projectId: 'kpikomida',
    databaseURL: 'https://kpikomida-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpikomida.firebasestorage.app',
    iosBundleId: 'id.my.comdev.todolist.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ncymf15NZpArPBXK2Ss5jPLzZWC4ye4',
    appId: '1:639013215151:ios:562d2f22911dc4e80aad5a',
    messagingSenderId: '639013215151',
    projectId: 'kpikomida',
    databaseURL: 'https://kpikomida-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpikomida.firebasestorage.app',
    iosBundleId: 'id.my.comdev.todolist.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPJdAkP6VA4TIudb9_IIU7qe3S0r1_nog',
    appId: '1:639013215151:web:26965ae89a9ac6cc0aad5a',
    messagingSenderId: '639013215151',
    projectId: 'kpikomida',
    authDomain: 'kpikomida.firebaseapp.com',
    databaseURL: 'https://kpikomida-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpikomida.firebasestorage.app',
    measurementId: 'G-YHXNQ1XZMW',
  );

}